### PR TITLE
Slurm partition qos

### PR DESCRIPTION
**Pull request by anderbubble**
I added `{partition}` and `{qos}` values for Slurm templates

### CODE REVIEW

**Comment by mbmilligan** [comment]
Thanks @anderbubble -- I've made you wait long enough on this, so I'm going ahead and pulling. However, I am going to change how you defined the 'homedir' value to use the req_foo trait method. That will keep it easy to override in subclasses.

**Comment by anderbubble** [comment]
@mbmilligan Will it still default to what comes out of pwd? Cause I don't know how else you'd define it to work that way using a trait specified in the config file.

I'm new to traits, though, so I could easily be missing something.

**Comment by mbmilligan** [comment]
It should have exactly the same behavior as what you provided in this PR. See the following commit (https://github.com/mbmilligan/batchspawner/commit/4f11e01875038ce4e9188ba0a6720f1e1d63e81b) -- I just moved the getpwnam call into a trait default value function.

**Comment by anderbubble** [comment]
Sounds great! Thanks for merging.

**Pull request merged**
